spring:
  application:
    name: proy-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/denisusmpWS/developerSOA.git
          force-pull: true
server:
  port: 5005
